version: "3.3"

services:

  backend:
    image: alimizan/petclinic-backend:latest
    ports:
      - 9966:9966
    networks:
      - app
    container_name: backend

  frontend:
    image: alimizan/spring-petclinic-angular-with-ip:latest
    depends_on:
      - backend
    ports:
      - 4200:4200
    networks:
      - app
    container_name: frontend

networks:
  app:

